// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OFTI_Service.Entities;

namespace OFTI_Service.Migrations
{
    [DbContext(typeof(UsersWorkerDbContext))]
    [Migration("20211119133117_addnewtable")]
    partial class addnewtable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("OFTI_Service.Entities.UsersWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FirstLogged")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLogged")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Master")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("UsersWorkers");
                });

            modelBuilder.Entity("OFTI_Service.Entities.WorkersAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberHouse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersWorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsersWorkerId");

                    b.ToTable("WorkersAddress");
                });

            modelBuilder.Entity("OFTI_Service.Entities.WorkersAddress", b =>
                {
                    b.HasOne("OFTI_Service.Entities.UsersWorker", null)
                        .WithMany("workersAddresses")
                        .HasForeignKey("UsersWorkerId");
                });

            modelBuilder.Entity("OFTI_Service.Entities.UsersWorker", b =>
                {
                    b.Navigation("workersAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
